print("Enter the intial velocity :",end=' ')
u= float(input())
print("Enter the acceleration :",end=' ')
a = float(input())
print("Enter the time taken :",end=' ')
t = float(input())
s = (u*t) + 0.5 * a * (t ** 2)
print("The value of s is :",s)
